# 端口
server:
  port: 8080

# 日志
logging:
  level:
    root: info #全局使用info级别
    com.example: trace #指定org.example包下的日志使用trace级别
  file:
    path: logs #日志保存路径
    name: logs/springboot.log #日志文件名
  pattern: #指定日志的格式
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n" #输出到文件的格式
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n" #输出到控制台的格式
  logback:
    rollingpolicy:
      max-history: 7
      max-file-size: 10MB

spring:
  datasource:
    username: root
    password: 'Aa123456'
    url: jdbc:mysql://123.57.83.114:3306/forum?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource #指定使用druid的连接池
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 30000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
  redis:
    host: 123.57.83.114
    port: 6379
    password: 'Aa123456.'
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 1000ms
  servlet:
    multipart:
      max-file-size: 10MB
  mvc:
    # 资源访问的前缀
    static-path-pattern: /${file.image-pattern-path}/**
  # 扫描的资源路径
  web:
    resources:
      static-locations: classpath:/resources/,classpath:/static/,file:${file.image-upload-path}

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 静态资源映射配置
file:
  image-pattern-path: files
  image-upload-path: D:/workspace/QASystem/QA_backed/uploads/images/

# jwt配置
jwt:
  header: Authorization
  secret: 2bbbd6fbdd4274ac5c5713bdb5666fefdc8a9773567d4b53eda59bf83289c4d7  # 加密秘钥
  expiration: 12000  # token有效期
  ignore-paths: ${api.prefix}/post/hello,${api.prefix}/login,${api.prefix}/register,${api.prefix}/logout,${api.prefix}/captcha/create

api:
  prefix: /api

# 时间格式
custom:
#  date-format: "yyyy-MM-dd"
  datetime-format: "yyyy-MM-dd HH:mm:ss"
#  sdf-fatetime-format: "yyyy-MM-dd HH:mm:ss.SSS"
