# 端口
server:
  port: 8080

# 日志
logging:
  level:
    root: info #全局使用info级别
    com.example: trace #指定org.example包下的日志使用trace级别
  file:
    path: logs #日志保存路径
    name: logs/springboot.log #日志文件名
  pattern: #指定日志的格式
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n" #输出到文件的格式
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n" #输出到控制台的格式
  logback:
    rollingpolicy:
      max-history: 7
      max-file-size: 10MB

spring:
  # mysql数据库配置
  datasource:
    username: root
    password: 'Aa123456'
    url: jdbc:mysql://123.57.83.114:3306/forum?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource #指定使用druid的连接池
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 30000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
  # redis数据库配置
  redis:
    host: 123.57.83.114
    port: 6379
    password: 'Aa123456.'
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 1000ms
  # 上传文件最大大小
  servlet:
    multipart:
      max-file-size: 10MB
  # 静态资源映射
  mvc:
    # 资源访问的前缀
    static-path-pattern: ${file.pattern-path}/**
  # 邮箱配置
  mail:
    email: j70028333@126.com
    host: smtp.126.com
    port: 465
    username: j70028333@126.com
    password: WEXYEPBWMKUYWTUS
    # 邮箱验证码有效时间
    code:
      expiration: 300
  # 扫描的资源路径
  web:
    resources:
      static-locations: classpath:/resources/,classpath:/static/,file:${file.upload-path}
  # JSON构造格式
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 静态资源映射配置
file:
  upload-path: D:/WorkSpace/play/uploads/
  pattern-path: /files
  avatar:
    # 头像文件大小 200KB
    max-size: 204800

# jwt配置
jwt:
  header: Authorization
  secret: 2bbbd6fbdd4274ac5c5713bdb5666fefdc8a9773567d4b53eda59bf83289c4d7  # 加密秘钥
  expiration: 7200  # token有效期
  ignore-paths:
    # 静态资源
    - /files/**
    # 帖子列表
    - ${api.prefix}/post/list
    # 账号密码登录
    - ${api.prefix}/user/login
    # 账号密码登录
    - ${api.prefix}/user/emailLogin
    # 注册
    - ${api.prefix}/user/register
    # 图片验证码
    - ${api.prefix}/captcha/create
    # 注册邮箱验证码
    - ${api.prefix}/email/sendRegisterCode
    # 登录邮箱验证码
    - ${api.prefix}/email/sendLoginCode


# 接口前缀
api:
  prefix: /api

# 时间格式
custom:
#  date-format: "yyyy-MM-dd"
  datetime-format: "yyyy-MM-dd HH:mm:ss"
#  sdf-fatetime-format: "yyyy-MM-dd HH:mm:ss.SSS"
